# Generated by Django 5.2.11 on 2026-02-23 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_kick', models.IntegerField(default=0)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sessions/videos/')),
                ('mode', models.CharField(choices=[('default', 'Default'), ('live', 'Live')], default='default', max_length=20)),
                ('is_story', models.BooleanField(default=False)),
                ('is_shared_to_leaderboard', models.BooleanField(default=False)),
                ('session_duration', models.IntegerField(default=5)),
                ('countdown_time', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
