# Generated by Django 5.2.11 on 2026-03-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
