# Generated by Django 5.2.11 on 2026-03-03 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0003_rename_name_trainingcategory_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pac', models.IntegerField(default=0)),
                ('sho', models.IntegerField(default=0)),
                ('pas', models.IntegerField(default=0)),
                ('dri', models.IntegerField(default=0)),
                ('_def', models.IntegerField(default=0)),
                ('phy', models.IntegerField(default=0)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('total_duration_sec', models.FloatField(default=0.0)),
                ('fps', models.FloatField(default=0.0)),
                ('total_players_detected', models.IntegerField(default=0)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
