# Generated by Django 5.2.11 on 2026-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='entry_fee',
        ),
        migrations.AddField(
            model_name='tournament',
            name='product_purchase_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
