# Generated by Django 5.2.11 on 2026-03-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
