# Generated by Django 5.2.11 on 2026-03-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingsession_trainingcategory_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingcategory',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingcategory'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='training/sessions/'),
        ),
    ]
