# Generated by Django 5.2.11 on 2026-03-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_rename_name_trainingcategory_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcompletion',
            name='training_video',
        ),
        migrations.RenameField(
            model_name='trainingsession',
            old_name='time_minutes',
            new_name='score_required',
        ),
        migrations.AddField(
            model_name='trainingcompletion',
            name='training_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='training.trainingsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TrainingVideo',
        ),
    ]
