# Generated by Django 5.2.11 on 2026-03-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_trainingcompletion_training_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='training/videos/'),
        ),
    ]
